// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"

class Vtop__Syms;
class Vtop___024unit;


class Vtop___024root final : public VerilatedModule {
  public:
    // CELLS
    Vtop___024unit* __PVT____024unit;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        CData/*0:0*/ top__DOT__inv_flag;
        CData/*0:0*/ top__DOT___AXI_arbiter_io_axi_ar_arvalid;
        CData/*0:0*/ top__DOT___AXI_arbiter_io_axi_r_rready;
        CData/*0:0*/ top__DOT___AXI_arbiter_io_axi_aw_awvalid;
        CData/*3:0*/ top__DOT___AXI_arbiter_io_axi_w_wstrb;
        CData/*0:0*/ top__DOT___AXI_arbiter_io_axi_w_wvalid;
        CData/*0:0*/ top__DOT___AXI_arbiter_io_axi_b_bready;
        CData/*0:0*/ top__DOT___AXI_arbiter_io_uart_axi_aw_awvalid;
        CData/*3:0*/ top__DOT___AXI_arbiter_io_uart_axi_w_wstrb;
        CData/*0:0*/ top__DOT___AXI_arbiter_io_uart_axi_w_wvalid;
        CData/*0:0*/ top__DOT___AXI_arbiter_io_uart_axi_b_bready;
        CData/*0:0*/ top__DOT___AXI_arbiter_io_rtc_axi_ar_arvalid;
        CData/*0:0*/ top__DOT___AXI_arbiter_io_rtc_axi_r_rready;
        CData/*0:0*/ top__DOT___AXI_arbiter_io_lsu_axi_r_rvalid;
        CData/*0:0*/ top__DOT___AXI_arbiter_io_lsu_axi_b_bvalid;
        CData/*0:0*/ top__DOT___AXI_arbiter_io_ifu_axi_r_rvalid;
        CData/*0:0*/ top__DOT___WBU_io_out2ifu_valid;
        CData/*4:0*/ top__DOT___WBU_io_reg_waddr;
        CData/*1:0*/ top__DOT___WBU_io_csr_waddr_1;
        CData/*0:0*/ top__DOT___WBU_io_csr_wen_1;
        CData/*3:0*/ top__DOT___LSU_io_lsu_axi_w_wstrb;
        CData/*1:0*/ top__DOT___IDU_io_reg_data_csr_raddr;
        CData/*0:0*/ top__DOT__IFU__DOT__m2EXUstate;
        CData/*0:0*/ top__DOT__IFU__DOT__exu2in_reg;
        CData/*0:0*/ top__DOT__IFU__DOT__rready_reg;
        CData/*0:0*/ top__DOT__IFU__DOT__arvalid_reg;
        CData/*0:0*/ top__DOT__IDU__DOT__exu_data_mem_ren;
        CData/*0:0*/ top__DOT__IDU__DOT__exu_data_mem_wen;
        CData/*4:0*/ top__DOT__IDU__DOT__exu_data_reg_waddr;
        CData/*0:0*/ top__DOT__IDU__DOT__exu_data_reg_wen;
        CData/*4:0*/ top__DOT__IDU__DOT__exu_data_alu_op;
        CData/*3:0*/ top__DOT__IDU__DOT__exu_data_inst_type;
        CData/*0:0*/ top__DOT__IDU__DOT__exu_data_il_us;
        CData/*0:0*/ top__DOT__IDU__DOT__state;
        CData/*0:0*/ top__DOT__IDU__DOT__state_reg;
        CData/*4:0*/ top__DOT__IDU__DOT__casez_tmp;
        CData/*4:0*/ top__DOT__IDU__DOT__casez_tmp_0;
        CData/*0:0*/ top__DOT__IDU__DOT___GEN_12;
        CData/*0:0*/ top__DOT__IDU__DOT___GEN_13;
        CData/*0:0*/ top__DOT__IDU__DOT___GEN_14;
        CData/*0:0*/ top__DOT__IDU__DOT___GEN_15;
        CData/*0:0*/ top__DOT__IDU__DOT___GEN_17;
        CData/*0:0*/ top__DOT__IDU__DOT___GEN_20;
        CData/*0:0*/ top__DOT__EXU__DOT__m2IDUstate;
        CData/*0:0*/ top__DOT__EXU__DOT__state_reg;
        CData/*0:0*/ top__DOT__EXU__DOT__lsu_data_mem_ren;
        CData/*0:0*/ top__DOT__EXU__DOT__lsu_data_mem_wen;
        CData/*4:0*/ top__DOT__EXU__DOT__lsu_data_reg_waddr;
        CData/*0:0*/ top__DOT__EXU__DOT__lsu_data_reg_wen;
        CData/*3:0*/ top__DOT__EXU__DOT__lsu_data_inst_type;
        CData/*0:0*/ top__DOT__EXU__DOT__lsu_data_il_us;
        CData/*0:0*/ top__DOT__EXU__DOT___GEN_8;
        CData/*4:0*/ top__DOT__EXU__DOT____Vcellinp__alu__io_alu_op;
        CData/*0:0*/ top__DOT__EXU__DOT____VdfgTmp_h24c9dbcb__0;
        CData/*0:0*/ top__DOT__EXU__DOT____VdfgTmp_h6f82b556__0;
        CData/*4:0*/ top__DOT__EXU__DOT__alu__DOT____VdfgTmp_hdb870149__0;
        CData/*0:0*/ top__DOT__LSU__DOT__io_lsu_axi_b_bready_0;
        CData/*0:0*/ top__DOT__LSU__DOT__io_lsu_axi_r_rready_0;
        CData/*0:0*/ top__DOT__LSU__DOT__m2EXUstate;
        CData/*0:0*/ top__DOT__LSU__DOT__state_reg;
        CData/*0:0*/ top__DOT__LSU__DOT__io_out2wbu_valid_0;
        CData/*0:0*/ top__DOT__LSU__DOT__exu2in_valid;
    };
    struct {
        CData/*0:0*/ top__DOT__LSU__DOT__exu2in_valid_reg;
        CData/*0:0*/ top__DOT__LSU__DOT__rready_reg;
        CData/*0:0*/ top__DOT__LSU__DOT__mem_ren_reg;
        CData/*0:0*/ top__DOT__LSU__DOT__io_lsu_axi_ar_arvalid_0;
        CData/*0:0*/ top__DOT__LSU__DOT__rvalid_reg;
        CData/*0:0*/ top__DOT__LSU__DOT__bready_reg;
        CData/*0:0*/ top__DOT__LSU__DOT__mem_wen_reg;
        CData/*0:0*/ top__DOT__LSU__DOT__m_wen_reg_delay;
        CData/*0:0*/ top__DOT__LSU__DOT__io_lsu_axi_aw_awvalid_0;
        CData/*0:0*/ top__DOT__LSU__DOT___GEN_2;
        CData/*0:0*/ top__DOT__LSU__DOT__io_lsu_axi_w_wvalid_0;
        CData/*0:0*/ top__DOT__LSU__DOT__bvalid_reg;
        CData/*4:0*/ top__DOT__LSU__DOT__wbu_data_reg_waddr;
        CData/*0:0*/ top__DOT__LSU__DOT__wbu_data_reg_wen;
        CData/*3:0*/ top__DOT__LSU__DOT__wbu_data_inst_type;
        CData/*1:0*/ top__DOT__LSU__DOT__wbu_data_mem_bresp;
        CData/*1:0*/ top__DOT__LSU__DOT__wbu_data_mem_rresp;
        CData/*0:0*/ top__DOT__LSU__DOT___GEN_3;
        CData/*0:0*/ top__DOT__LSU__DOT___GEN_4;
        CData/*0:0*/ top__DOT__LSU__DOT___GEN_5;
        CData/*0:0*/ top__DOT__LSU__DOT___GEN_6;
        CData/*0:0*/ top__DOT__LSU__DOT____VdfgTmp_h791150d4__0;
        CData/*0:0*/ top__DOT__LSU__DOT____VdfgTmp_hd83711f5__0;
        CData/*4:0*/ top__DOT__LSU__DOT__delay_ar__DOT__shiftReg;
        CData/*4:0*/ top__DOT__LSU__DOT__delay_ar__DOT__counter;
        CData/*0:0*/ top__DOT__LSU__DOT__delay_ar__DOT___GEN_0;
        CData/*4:0*/ top__DOT__LSU__DOT__delay_r__DOT__shiftReg;
        CData/*4:0*/ top__DOT__LSU__DOT__delay_r__DOT__counter;
        CData/*0:0*/ top__DOT__LSU__DOT__delay_r__DOT___GEN_0;
        CData/*4:0*/ top__DOT__LSU__DOT__delay_aw__DOT__shiftReg;
        CData/*4:0*/ top__DOT__LSU__DOT__delay_aw__DOT__counter;
        CData/*0:0*/ top__DOT__LSU__DOT__delay_aw__DOT___GEN_0;
        CData/*4:0*/ top__DOT__LSU__DOT__delay_w__DOT__shiftReg;
        CData/*4:0*/ top__DOT__LSU__DOT__delay_w__DOT__counter;
        CData/*0:0*/ top__DOT__LSU__DOT__delay_w__DOT___GEN_0;
        CData/*4:0*/ top__DOT__LSU__DOT__delay_b__DOT__shiftReg;
        CData/*4:0*/ top__DOT__LSU__DOT__delay_b__DOT__counter;
        CData/*0:0*/ top__DOT__LSU__DOT__delay_b__DOT___GEN_0;
        CData/*0:0*/ top__DOT__WBU__DOT__m2LSUstate;
        CData/*0:0*/ top__DOT__WBU__DOT___GEN_11;
        CData/*0:0*/ top__DOT__WBU__DOT___GEN_12;
        CData/*0:0*/ top__DOT__WBU__DOT___GEN_13;
        CData/*0:0*/ top__DOT__WBU__DOT___GEN_14;
        CData/*0:0*/ top__DOT__WBU__DOT___GEN_15;
        CData/*0:0*/ top__DOT__WBU__DOT___GEN_17;
        CData/*0:0*/ top__DOT__WBU__DOT___GEN_19;
        CData/*0:0*/ top__DOT__WBU__DOT___GEN_20;
        CData/*0:0*/ top__DOT__WBU__DOT____VdfgTmp_hc8eaa83d__0;
        CData/*0:0*/ top__DOT__WBU__DOT____VdfgTmp_h2b8a6806__0;
        CData/*0:0*/ top__DOT__WBU__DOT____VdfgTmp_h43fa6f6f__0;
        CData/*0:0*/ top__DOT__Reg__DOT___GEN;
        CData/*0:0*/ top__DOT__AXI_arbiter__DOT___GEN;
        CData/*0:0*/ top__DOT__AXI_arbiter__DOT___GEN_0;
        CData/*0:0*/ top__DOT__AXI_arbiter__DOT___GEN_1;
        CData/*0:0*/ top__DOT__AXI_arbiter__DOT___GEN_2;
        CData/*0:0*/ top__DOT__AXI_arbiter__DOT___GEN_3;
        CData/*0:0*/ top__DOT__AXI_arbiter__DOT___GEN_4;
        CData/*0:0*/ top__DOT__AXI_arbiter__DOT___GEN_5;
        CData/*0:0*/ top__DOT__AXI_arbiter__DOT___GEN_6;
        CData/*0:0*/ top__DOT__AXI_arbiter__DOT___GEN_7;
        CData/*0:0*/ top__DOT__AXI_arbiter__DOT____VdfgTmp_hc8f955bb__0;
        CData/*0:0*/ top__DOT__AXI_arbiter__DOT____VdfgTmp_ha75ffa7c__0;
        CData/*0:0*/ top__DOT__AXI_arbiter__DOT____VdfgTmp_hf6818992__0;
        CData/*0:0*/ top__DOT__AXI_arbiter__DOT____VdfgTmp_hb0ea07fc__0;
    };
    struct {
        CData/*0:0*/ top__DOT__AXI_arbiter__DOT____VdfgTmp_hff3363a0__0;
        CData/*0:0*/ top__DOT__AXI_arbiter__DOT____VdfgTmp_h76d06acc__0;
        CData/*0:0*/ top__DOT__AXI_arbiter__DOT____VdfgTmp_ha6f808b4__0;
        CData/*0:0*/ top__DOT__AXI_arbiter__DOT____VdfgTmp_h0eb34983__0;
        CData/*0:0*/ top__DOT__RTC__DOT__rvalid_reg;
        CData/*1:0*/ top__DOT__RTC__DOT__rresp_reg;
        CData/*0:0*/ top__DOT__RTC__DOT__arvalid_reg;
        CData/*0:0*/ top__DOT__RTC__DOT___GEN;
        CData/*0:0*/ top__DOT__RTC__DOT__rvalid_en;
        CData/*4:0*/ top__DOT__RTC__DOT__delay__DOT__shiftReg;
        CData/*4:0*/ top__DOT__RTC__DOT__delay__DOT__counter;
        CData/*0:0*/ top__DOT__RTC__DOT__delay__DOT___GEN_0;
        CData/*0:0*/ top__DOT__SRAM__DOT__rvalid_reg;
        CData/*1:0*/ top__DOT__SRAM__DOT__rresp_reg;
        CData/*0:0*/ top__DOT__SRAM__DOT__arvalid_reg;
        CData/*0:0*/ top__DOT__SRAM__DOT__bvalid_reg;
        CData/*1:0*/ top__DOT__SRAM__DOT__bresp_reg;
        CData/*3:0*/ top__DOT__SRAM__DOT__wstrb_reg;
        CData/*0:0*/ top__DOT__SRAM__DOT__awvalid_reg;
        CData/*0:0*/ top__DOT__SRAM__DOT__wvalid_reg;
        CData/*0:0*/ top__DOT__SRAM__DOT___GEN_0;
        CData/*0:0*/ top__DOT__SRAM__DOT__rvalid_en;
        CData/*0:0*/ top__DOT__SRAM__DOT___GEN_1;
        CData/*0:0*/ top__DOT__SRAM__DOT__bvalid_en;
        CData/*4:0*/ top__DOT__SRAM__DOT__delay__DOT__shiftReg;
        CData/*4:0*/ top__DOT__SRAM__DOT__delay__DOT__counter;
        CData/*0:0*/ top__DOT__SRAM__DOT__delay__DOT___GEN_0;
        CData/*4:0*/ top__DOT__SRAM__DOT__delay_w__DOT__shiftReg;
        CData/*4:0*/ top__DOT__SRAM__DOT__delay_w__DOT__counter;
        CData/*0:0*/ top__DOT__SRAM__DOT__delay_w__DOT___GEN_0;
        CData/*0:0*/ top__DOT__UART__DOT__bvalid_reg;
        CData/*1:0*/ top__DOT__UART__DOT__bresp_reg;
        CData/*3:0*/ top__DOT__UART__DOT__wstrb_reg;
        CData/*0:0*/ top__DOT__UART__DOT__awvalid_reg;
        CData/*0:0*/ top__DOT__UART__DOT__wvalid_reg;
        CData/*0:0*/ top__DOT__UART__DOT___GEN;
        CData/*0:0*/ top__DOT__UART__DOT__bvalid_en;
        CData/*4:0*/ top__DOT__UART__DOT__delay_w__DOT__shiftReg;
        CData/*4:0*/ top__DOT__UART__DOT__delay_w__DOT__counter;
        CData/*0:0*/ top__DOT__UART__DOT__delay_w__DOT___GEN_0;
        CData/*0:0*/ __VdfgTmp_hb1f015da__0;
        CData/*4:0*/ __VdfgTmp_h38812605__0;
        CData/*0:0*/ __Vdly__top__DOT__IFU__DOT__m2EXUstate;
        CData/*0:0*/ __Vdly__top__DOT__IFU__DOT__arvalid_reg;
        CData/*0:0*/ __Vtrigrprev__TOP__clock;
        CData/*0:0*/ __VactDidInit;
        CData/*0:0*/ __VactContinue;
        IData/*31:0*/ top__DOT___SRAM_io_axi_r_rdata;
        IData/*31:0*/ top__DOT___AXI_arbiter_io_axi_aw_awaddr;
        IData/*31:0*/ top__DOT___AXI_arbiter_io_uart_axi_aw_awaddr;
        IData/*31:0*/ top__DOT___AXI_arbiter_io_lsu_axi_r_rdata;
        IData/*31:0*/ top__DOT___WBU_io_reg_wdata;
        IData/*31:0*/ top__DOT___WBU_io_csr_wdata_1;
        IData/*31:0*/ top__DOT___LSU_io_lsu_axi_ar_araddr;
        IData/*31:0*/ top__DOT___LSU_io_lsu_axi_w_wdata;
        IData/*31:0*/ top__DOT___LSU_io_lsu_axi_aw_awaddr;
        IData/*31:0*/ top__DOT__IFU__DOT__io_out_bits_pc_0;
        IData/*31:0*/ top__DOT__IFU__DOT__indata_dnpc;
        IData/*31:0*/ top__DOT__IFU__DOT__ardata_reg;
        IData/*31:0*/ top__DOT__IFU__DOT__inst_reg;
        IData/*31:0*/ top__DOT__IFU__DOT__io_out_bits_pc_REG;
        IData/*31:0*/ top__DOT__IDU__DOT__exu_data_snpc;
        IData/*31:0*/ top__DOT__IDU__DOT__exu_data_pc;
        IData/*31:0*/ top__DOT__IDU__DOT__exu_data_m_rmask;
    };
    struct {
        IData/*31:0*/ top__DOT__IDU__DOT__exu_data_m_wmask;
        IData/*31:0*/ top__DOT__IDU__DOT__exu_data_src1;
        IData/*31:0*/ top__DOT__IDU__DOT__exu_data_src2;
        IData/*31:0*/ top__DOT__IDU__DOT__exu_data_csr;
        IData/*31:0*/ top__DOT__IDU__DOT__exu_data_csr_a5;
        IData/*31:0*/ top__DOT__IDU__DOT__exu_data_mstatus;
        IData/*31:0*/ top__DOT__IDU__DOT__exu_data_imm;
        IData/*31:0*/ top__DOT__IDU__DOT__csr_imm;
        IData/*31:0*/ top__DOT__EXU__DOT___alu_io_result;
        IData/*31:0*/ top__DOT__EXU__DOT__alu_result_reg;
        IData/*31:0*/ top__DOT__EXU__DOT__lsu_data_snpc;
        IData/*31:0*/ top__DOT__EXU__DOT__lsu_data_pc;
        IData/*31:0*/ top__DOT__EXU__DOT__lsu_data_m_rmask;
        IData/*31:0*/ top__DOT__EXU__DOT__lsu_data_m_wmask;
        IData/*31:0*/ top__DOT__EXU__DOT__lsu_data_src1;
        IData/*31:0*/ top__DOT__EXU__DOT__lsu_data_src2;
        IData/*31:0*/ top__DOT__EXU__DOT__lsu_data_csr;
        IData/*31:0*/ top__DOT__EXU__DOT__lsu_data_csr_a5;
        IData/*31:0*/ top__DOT__EXU__DOT__lsu_data_mstatus;
        IData/*31:0*/ top__DOT__EXU__DOT__lsu_data_imm;
        IData/*31:0*/ top__DOT__EXU__DOT__lsu_data_alu_result;
        IData/*31:0*/ top__DOT__EXU__DOT____Vcellinp__alu__io_src2;
        IData/*31:0*/ top__DOT__EXU__DOT____Vcellinp__alu__io_src1;
        IData/*31:0*/ top__DOT__LSU__DOT__mem_raddr_reg;
        IData/*31:0*/ top__DOT__LSU__DOT__mem_rmask_reg;
        IData/*31:0*/ top__DOT__LSU__DOT__mem_awaddr_reg;
        IData/*31:0*/ top__DOT__LSU__DOT__mem_wstrb_reg;
        IData/*31:0*/ top__DOT__LSU__DOT__mem_wdata_reg;
        IData/*31:0*/ top__DOT__LSU__DOT___GEN_1;
        IData/*31:0*/ top__DOT__LSU__DOT__wbu_data_snpc;
        IData/*31:0*/ top__DOT__LSU__DOT__wbu_data_pc;
        IData/*31:0*/ top__DOT__LSU__DOT__wbu_data_src1;
        IData/*31:0*/ top__DOT__LSU__DOT__wbu_data_csr;
        IData/*31:0*/ top__DOT__LSU__DOT__wbu_data_csr_a5;
        IData/*31:0*/ top__DOT__LSU__DOT__wbu_data_mstatus;
        IData/*31:0*/ top__DOT__LSU__DOT__wbu_data_imm;
        IData/*31:0*/ top__DOT__LSU__DOT__wbu_data_mem_rdata;
        IData/*31:0*/ top__DOT__LSU__DOT__wbu_data_alu_result;
        IData/*31:0*/ top__DOT__LSU__DOT__delay_ar__DOT__dataReg;
        IData/*31:0*/ top__DOT__LSU__DOT__delay_r__DOT__dataReg;
        IData/*31:0*/ top__DOT__LSU__DOT__delay_aw__DOT__dataReg;
        IData/*31:0*/ top__DOT__LSU__DOT__delay_w__DOT__dataReg;
        IData/*31:0*/ top__DOT__LSU__DOT__delay_b__DOT__dataReg;
        IData/*31:0*/ top__DOT__WBU__DOT__ifu_outdata_dnpc;
        IData/*31:0*/ top__DOT__WBU__DOT__lastdnpc;
        IData/*31:0*/ top__DOT__Reg__DOT__csr_0;
        IData/*31:0*/ top__DOT__Reg__DOT__csr_1;
        IData/*31:0*/ top__DOT__Reg__DOT__csr_2;
        IData/*31:0*/ top__DOT__Reg__DOT__csr_3;
        IData/*31:0*/ top__DOT__Reg__DOT__reg_0;
        IData/*31:0*/ top__DOT__Reg__DOT__reg_1;
        IData/*31:0*/ top__DOT__Reg__DOT__reg_2;
        IData/*31:0*/ top__DOT__Reg__DOT__reg_3;
        IData/*31:0*/ top__DOT__Reg__DOT__reg_4;
        IData/*31:0*/ top__DOT__Reg__DOT__reg_5;
        IData/*31:0*/ top__DOT__Reg__DOT__reg_6;
        IData/*31:0*/ top__DOT__Reg__DOT__reg_7;
        IData/*31:0*/ top__DOT__Reg__DOT__reg_8;
        IData/*31:0*/ top__DOT__Reg__DOT__reg_9;
        IData/*31:0*/ top__DOT__Reg__DOT__reg_10;
        IData/*31:0*/ top__DOT__Reg__DOT__reg_11;
        IData/*31:0*/ top__DOT__Reg__DOT__reg_12;
        IData/*31:0*/ top__DOT__Reg__DOT__reg_13;
        IData/*31:0*/ top__DOT__Reg__DOT__reg_14;
    };
    struct {
        IData/*31:0*/ top__DOT__Reg__DOT__reg_15;
        IData/*31:0*/ top__DOT__Reg__DOT__reg_16;
        IData/*31:0*/ top__DOT__Reg__DOT__reg_17;
        IData/*31:0*/ top__DOT__Reg__DOT__reg_18;
        IData/*31:0*/ top__DOT__Reg__DOT__reg_19;
        IData/*31:0*/ top__DOT__Reg__DOT__reg_20;
        IData/*31:0*/ top__DOT__Reg__DOT__reg_21;
        IData/*31:0*/ top__DOT__Reg__DOT__reg_22;
        IData/*31:0*/ top__DOT__Reg__DOT__reg_23;
        IData/*31:0*/ top__DOT__Reg__DOT__reg_24;
        IData/*31:0*/ top__DOT__Reg__DOT__reg_25;
        IData/*31:0*/ top__DOT__Reg__DOT__reg_26;
        IData/*31:0*/ top__DOT__Reg__DOT__reg_27;
        IData/*31:0*/ top__DOT__Reg__DOT__reg_28;
        IData/*31:0*/ top__DOT__Reg__DOT__reg_29;
        IData/*31:0*/ top__DOT__Reg__DOT__reg_30;
        IData/*31:0*/ top__DOT__Reg__DOT__reg_31;
        IData/*31:0*/ top__DOT__Reg__DOT__casez_tmp;
        IData/*31:0*/ top__DOT__Reg__DOT__casez_tmp_0;
        IData/*31:0*/ top__DOT__RTC__DOT__rtc_raddr;
        IData/*31:0*/ top__DOT__RTC__DOT__rdata_reg;
        IData/*31:0*/ top__DOT__RTC__DOT__delay__DOT__dataReg;
        IData/*31:0*/ top__DOT__SRAM__DOT___m_m_rdata;
        IData/*31:0*/ top__DOT__SRAM__DOT__rdata_reg;
        IData/*31:0*/ top__DOT__SRAM__DOT__waddr_reg;
        IData/*31:0*/ top__DOT__SRAM__DOT___GEN;
        IData/*31:0*/ top__DOT__SRAM__DOT__delay__DOT__dataReg;
        IData/*31:0*/ top__DOT__SRAM__DOT__delay_w__DOT__dataReg;
        IData/*31:0*/ top__DOT__UART__DOT__waddr_reg;
        IData/*31:0*/ top__DOT__UART__DOT__delay_w__DOT__dataReg;
        IData/*31:0*/ __VdfgTmp_h149de1f0__0;
        IData/*31:0*/ __Vfunc_vlg_pmem_read__1__Vfuncout;
        IData/*31:0*/ __VstlIterCount;
        IData/*31:0*/ __Vtrigrprev__TOP__top__DOT__IFU__DOT__inst_reg;
        IData/*31:0*/ __VactIterCount;
        QData/*63:0*/ top__DOT__RTC__DOT__mtime;
        VlUnpacked<CData/*0:0*/, 3> __Vm_traceActivity;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<2> __VactTriggered;
    VlTriggerVec<2> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);


#endif  // guard
