#ifndef __CONFIG_H__
#define __CONFIG_H__

CONFIG_MODE 1  //0 --batch 1=--log
CONFIG_ITRACE=1
CONFIG_ITRACE_COND="true"
ITRACE_COND="true"
CONFIG_IQUEUE=1
CONFIG_TARGET_NATIVE_ELF=1
__GUEST_ISA__ "riscv32"=
CONFIG_FTRACE=1
CONFIG_FTRACE_COND="true"
FTRACE_COND="ture"
CONFIG_DIFFTEST=1
#endif

